services:
  - type: web
    name: chat-service
    env: docker
    plan: starter
    repo: https://github.com/your-org/your-repo
    dockerfilePath: chat-service/Dockerfile
    buildFilter:
      paths:
        - chat-service/**
    region: oregon
    ports:
      - 8000

  - type: web
    name: product-service
    env: docker
    plan: starter
    repo: https://github.com/your-org/your-repo
    dockerfilePath: product-service/Dockerfile
    buildFilter:
      paths:
        - product-service/**
    region: oregon
    ports:
      - 8001

  - type: web
    name: order-service
    env: docker
    plan: starter
    repo: https://github.com/your-org/your-repo
    dockerfilePath: order-service/Dockerfile
    buildFilter:
      paths:
        - order-service/**
    region: oregon
    ports:
      - 8002

  - type: web
    name: mock-api
    env: docker
    plan: starter
    repo: https://github.com/your-org/your-repo
    dockerfilePath: order-service/Dockerfile
    buildFilter:
      paths:
        - order-service/**
    startCommand: uvicorn services.mock_api:app --host 0.0.0.0 --port 4000
    region: oregon
    ports:
      - 4000

  - type: web
    name: frontend
    env: docker
    plan: starter
    repo: https://github.com/your-org/your-repo
    dockerfilePath: frontend/Dockerfile
    buildFilter:
      paths:
        - frontend/**
    region: oregon
    ports:
      - 3000
